#:schema node_modules/wrangler/config-schema.json
name = "twikoo-cloudflare"
main = "src/index.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "twikoo"
database_id = "4ad8969f-c28a-4d4c-950e-ff1316adfc22"

[vars]
SITE_URL = "https://nguki.com/"

[dev]
port = 5000
